### ISSUE TITLE
PlaceMark/Style/LineStyle/width is not correctly being set for multipoints

### ISSUE THREAD

**Issue by spyhunter99** [missioncommand/mil-sym-android#30] opened 2015-06-20 00:19 UTC
When rendering a multipoint no fire area, the line width is set for the first placemark, but not for all of them. This only appears to affect multipoints with cross hatches such as
obstacle restricted area
radioactive area
biologically contaminated area

ares without the cross hatch are ok

**Comment by mdeutch3** [comment] 2015-06-22 16:58
I don't see a problem rendering NFA. The cross hatch lines are held at a constant thickness of 1 by design, if that is what you are referring to.

**Comment by spyhunter99** [comment] 2015-06-22 23:12
Is there any way to adjust the line width? Everything on the rendered NFA is 1 pixel wide. On an 8inch tablet at 2x HD, it's almost invisible

**Comment by michael-spinelli** [comment] 2015-06-23 14:12
He's got a point Mike.  He's using small displays with a high resolution.  Maybe we could do "Math.round(linewidth/2.0)" for hash fill line width?

**Comment by mdeutch3** [comment] 2015-06-23 14:50
The hatch line width is now 1/2 the tactical graphic line width.

**Comment by michael-spinelli** [comment] 2015-06-24 14:55
fix will be in .64 release

**Comment by spyhunter99** [comment] 2015-06-26 20:36
Need to reopen this. Line width is now fixed, but the colors are not set correctly. Obstacle restricted area is not showing up green. All multipoints flagged with hostile, also render as black now. WIth RenderAsIcon set to true, correct colors are rendered. The problem is that the kml only produces a line color as ff000000

**Comment by mdeutch3** [comment] 2015-06-26 22:43
I'm not seeing a problem setting the line color for Obstacle Restricted Area. Are you setting the line color using MilStdAttributes?
            attributes.put(MilStdAttributes.LineColor, linecolor);
...
                strRender = sec.RenderSymbol("id", "name", "description", defaultText, controlPtsStr, altitudeMode, scale, rectStr, modifiers, attributes, format, rev);

**Comment by spyhunter99** [comment] 2015-06-27 00:33
sorry I guess this isn't strictly related to this ticket, but more of an issue with the .64 release. Example coming shortly. Anyhow

Obstacle restricted area, according to the icon, should be green. here's the log output and input parameters


`render multipoint KML with  attrib:2 mods:0 font:14 id=fe76d2c2-7e97-49ae-af4a-c74b0ba2fe3e name=N/A code=GFMPOGR-------- points=-76.339359,39.632663 -76.331119,39.625457 -76.36116,39.612565  altmode=relativeToGround scale=13250.0 bbox=-76.414632,39.551706,-76.194906,39.657513
D/RendererService(31344): Line Color not defined
D/RendererService(31344): Fill Color not defined
D/RendererService(31344): Font Size not defined
D/RendererService(31344): Pixel Size not defined
D/RendererService(31344): Scale not defined
D/RendererService(31344): Keep Unit Ratio not defined
D/RendererService(31344): Alpha not defined
D/RendererService(31344): Outline Symbol not defined
D/RendererService(31344): Outline Color not defined
D/RendererService(31344): Draw as icon not defined
D/RendererService(31344): Symbology Standard not defined
D/RendererService(31344): Quantity not defined
D/RendererService(31344): Additional Info 1 not defined
D/RendererService(31344): Additional Info 2 not defined
D/RendererService(31344): Additional Info 3 not defined
D/RendererService(31344): Hostile not defined
D/RendererService(31344): Direction of movement not defined
D/RendererService(31344): Unique Designation 1 not defined
D/RendererService(31344): Unique Designation 2 not defined
D/RendererService(31344): Equipment Type not defined
D/RendererService(31344): DTG not defined
D/RendererService(31344): DTG not defined
D/RendererService(31344): Altitude or depth not defined
D/RendererService(31344): Location not defined
D/RendererService(31344): Distance not defined
D/RendererService(31344): Azimuth not defined
D/RendererService(31344): Length not defined
D/RendererService(31344): Width not defined
D/RendererService(31344): Radius not defined
D/RendererService(31344): Angle not defined
I/dalvikvm(31344): Jit: resizing JitTable from 8192 to 16384
I/System.out(31344): <Folder id="fe76d2c2-7e97-49ae-af4a-c74b0ba2fe3e"><name><![CDATA[N/A]]></name><visibility>1</visibility><Placemark><description><![CDATA[<b>N/A</b><br/>Obstacle Restricted Area]]></description><Style id="lineColor"><LineStyle><color>ff000000</color><colorMode>normal</colorMode><width>12</width></LineStyle></Style><MultiGeometry><LineString><tessellate>1</tessellate><altitudeMode>clampToGround</altitudeMode><coordinates>-76.33939571,39.63281553 -76.33808093,39.63163141 -76.33896015,39.6299398 -76.33654704,39.63027812 -76.3354515,39.62926316 -76.33391772,39.62790987 -76.33501632,39.62621826 -76.33260312,39.62672575 -76.33128857,39.62554162 -76.33128857,39.62554162 -76.33326329,39.62486498 -76.33523603,39.62587994 -76.33523816,39.62401917 -76.33677416,39.62334253 -76.33874894,39.62249673 -76.3407217,39.62351169 -76.34072368,39.62165092 -76.34072368,39.62165092 -76.34269836,39.62080512 -76.34467096,39.62198925 -76.3444537,39.61995932 -76.3444537,39.61995932 -76.34642829,39.61911351 -76.3484009,39.62029764 -76.34840268,39.61843687 -76.34840268,39.61843687 -76.35015788,39.61759107 -76.35234997,39.61860603 -76.35213234,39.61674526 -76.35213234,39.61674526 -76.35410675,39.61589946 -76.35607954,39.61691442 -76.35608111,39.61505365 -76.35608111,39.61505365 -76.35783614,39.61420785 -76.3600281,39.61539198 -76.35981027,39.61353121 -76.36134593,39.6126854 -76.36134593,39.6126854 -76.36002916,39.61403869 -76.35761726,39.61370037 -76.35871234,39.61539198 -76.35761504,39.61640694 -76.35607897,39.61759107 -76.35366697,39.61725274 -76.35476201,39.61894435 -76.35476201,39.61894435 -76.35322569,39.62029764 -76.35081376,39.61979016 -76.35190877,39.62148176 -76.35190877,39.62148176 -76.35037233,39.62283505 -76.34817966,39.62232757 -76.34905516,39.62418833 -76.34905516,39.62418833 -76.34773809,39.62537246 -76.34532586,39.62503414 -76.34620149,39.62672575 -76.34620149,39.62672575 -76.34488416,39.62807903 -76.34247203,39.62757155 -76.34334762,39.62926316 -76.34334762,39.62926316 -76.34203018,39.63061644 -76.33961798,39.63010896 -76.34049335,39.63196973 -76.33939571,39.63281553 </coordinates></LineString></MultiGeometry></Placemark><Placemark><description><![CDATA[<b>N/A</b><br/>Obstacle Restricted Area]]></description><Style id="lineColor"><LineStyle><color>ff000000</color><colorMode>normal</colorMode><width>6</width></LineStyle></Style><MultiGeometry><LineString><tessellate>1</tessellate><altitudeMode>clampToGround</altitudeMode><coordinates>-76.33939571,39.63281553 -76.33939571,39.63281553 </coordinates></LineString><LineString><tessellate>1</tessellate><altitudeMode>clampToGround</altitudeMode><coordinates>-76.33939571,39.63281553 -76.33939571,39.63281553 </coordinates></LineString><LineString><tessellate>1</tessellate><altitudeMode>clampToGround</altitudeMode><coordinates>-76.34049335,39.63196973 -76.34049335,39.63196973 </coordinates></LineString><LineString><tessellate>1</tessellate><altitudeMode>clampToGround</altitudeMode><coordinates>-76.36115047,39.61288628 -76.36114471,39.61279624 </coordinates></LineString><LineString><tessellate>1</tessellate><altitudeMode>clampToGround</altitudeMode><coordinates>-76.36113761,39.6126854 </coordinates></LineString><LineString><tessellate>1</tessellate><altitudeMode>clampToGround</altitudeMode><coordinates>-76.36112665,39.6126854 -76.36057811,39.61310831 </coordinates></LineString><LineString><tessellate>1</tessellate><altitudeMode>clampToGround</altitudeMode><coordinates>-76.35982842,39.61368627 -76.35947257,39.61396061 </coordinates></LineString><LineString><tessellate>1</tessellate><altitudeMode>clampToGround</altitudeMode><coordinates>-76.35860976,39.61462578 -76.35834731,39.61482811 </coordinates></LineString><LineString><tessellate>1</tessellate><altitudeMode>clampToGround</altitudeMode><coordinates>-76.35604326,39.6166043 -76.3558165,39.61677909 </coordinates></LineString><LineString><tessellate>1</tessellate><altitudeMode>clampToGround</altitudeMode><coordinates>-76.35496574,39.61743492 -76.35417799,39.61804216 </coordinates></LineString><LineString><tessellate>1</tessellate><altitudeMode>clampToGround</altitudeMode><coordinates>-76.35167516,39.6199714 -76.35117876,39.62035402 </coordinates></LineString><LineString><tessellate>1</tessellate><altitudeMode>clampToGround</altitudeMode><coordinates>-76.34851699,39.62240564 -76.34829638,39.62257567 </coordinates></LineString><LineString><tessellate>1</tessellate><altitudeMode>clampToGround</altitudeMode><coordinates>-76.33869202,39.62997739 </coordinates></LineString><LineString><tessellate>1</tessellate><altitudeMode>clampToGround</altitudeMode><coordinates>-76.33534924,39.62917294 -76.34467096,39.62198925 </coordinates></LineString><LineString><tessellate>1</tessellate><altitudeMode>clampToGround</altitudeMode><coordinates>-76.34467096,39.62198925 -76.34753788,39.61977958 </coordinates></LineString><LineString><tessellate>1</tessellate><altitudeMode>clampToGround</altitudeMode><coordinates>-76.34827401,39.61921219 -76.35029489,39.6176545 </coordinates></LineString><LineString><tessellate>1</tessellate><altitudeMode>clampToGround</altitudeMode><coordinates>-76.34072368,39.62165092 -76.34072368,39.62165092 </coordinates></LineString><LineString><tessellate>1</tessellate><altitudeMode>clampToGround</altitudeMode><coordinates>-76.34052248,39.62180599 -76.339275,39.62276739 </coordinates></LineString><LineString><tessellate>1</tessellate><altitudeMode>clampToGround</altitudeMode><coordinates>-76.33523603,39.62587994 -76.33523603,39.62587994 </coordinates></LineString><LineString><tessellate>1</tessellate><altitudeMode>clampToGround</altitudeMode><coordinates>-76.33471467,39.6262817 </coordinates></LineString><LineString><tessellate>1</tessellate><altitudeMode>clampToGround</altitudeMode><coordinates>-76.33128857,39.62554162 -76.33128857,39.62554162 </coordinates></LineString></MultiGeometry></Placemark></Folder>`

**Comment by spyhunter99** [comment] 2015-06-27 00:35
and here's the input for a hostile fortified area. note that in both cases, the line color is set to black and not provided as an input

`render multipoint KML with  attrib:2 mods:0 font:14 id=7cc364f5-1510-45c2-9f93-8183b592ba9b name=N/A code=GHGPGAF-------X points=-76.301164,39.6164 -76.299791,39.612763 -76.301851,39.596495 -76.323394,39.595239 -76.3276,39.596495  altmode=relativeToGround scale=13250.0 bbox=-76.414632,39.551706,-76.194906,39.657513
D/RendererService(31344): Line Color not defined
D/RendererService(31344): Fill Color not defined
D/RendererService(31344): Font Size not defined
D/RendererService(31344): Pixel Size not defined
D/RendererService(31344): Scale not defined
D/RendererService(31344): Keep Unit Ratio not defined
D/RendererService(31344): Alpha not defined
D/RendererService(31344): Outline Symbol not defined
D/RendererService(31344): Outline Color not defined
D/RendererService(31344): Draw as icon not defined
D/RendererService(31344): Symbology Standard not defined
D/RendererService(31344): Quantity not defined
D/RendererService(31344): Additional Info 1 not defined
D/RendererService(31344): Additional Info 2 not defined
D/RendererService(31344): Additional Info 3 not defined
D/RendererService(31344): Hostile not defined
D/RendererService(31344): Direction of movement not defined
D/RendererService(31344): Unique Designation 1 not defined
D/RendererService(31344): Unique Designation 2 not defined
D/RendererService(31344): Equipment Type not defined
D/RendererService(31344): DTG not defined
D/RendererService(31344): DTG not defined
D/RendererService(31344): Altitude or depth not defined
D/RendererService(31344): Location not defined
D/RendererService(31344): Distance not defined
D/RendererService(31344): Azimuth not defined
D/RendererService(31344): Length not defined
D/RendererService(31344): Width not defined
D/RendererService(31344): Radius not defined
D/RendererService(31344): Angle not defined
I/System.out(31344): <Folder id="7cc364f5-1510-45c2-9f93-8183b592ba9b"><name><![CDATA[N/A]]></name><visibility>1</visibility><Placemark><description><![CDATA[<b>N/A</b><br/>Fortified Area]]></description><Style id="lineColor"><LineStyle><color>ff000000</color><colorMode>normal</colorMode><width>12</width></LineStyle></Style><MultiGeometry><LineString><tessellate>1</tessellate><altitudeMode>clampToGround</altitudeMode><coordinates>-76.30125598,39.61640694 -76.30081988,39.61488449 -76.29862612,39.61539198 -76.29797108,39.61370037 -76.30016479,39.61319289 -76.29994606,39.61285457 -76.29994606,39.61285457 -76.30016785,39.61133212 -76.29797534,39.61116296 -76.29819745,39.60947135 -76.30038991,39.60964051 -76.30061169,39.60811806 -76.30083373,39.60642646 -76.29864108,39.60642646 -76.29886316,39.60473485 -76.30105575,39.60473485 -76.30105575,39.60473485 -76.3012775,39.6032124 -76.29908523,39.60304324 -76.29930729,39.60135164 -76.3014995,39.6015208 -76.3014995,39.6015208 -76.3017215,39.59982919 -76.29952934,39.59966003 -76.29975138,39.59796842 -76.30194348,39.59813758 -76.30194595,39.59661513 -76.30194595,39.59661513 -76.30413829,39.59661513 -76.30414097,39.59492353 -76.30633352,39.59475437 -76.30633088,39.59644597 -76.30852347,39.59627681 -76.31071605,39.59610765 -76.31049935,39.59441604 -76.31269162,39.59441604 -76.31268914,39.59610765 -76.31268939,39.59593849 -76.3148817,39.59593849 -76.31488413,39.59424688 -76.31707662,39.59407772 -76.31707425,39.59576933 -76.31707425,39.59576933 -76.31926679,39.59560017 -76.31926911,39.59390856 -76.32146159,39.5937394 -76.32145932,39.59543101 -76.32343261,39.59526185 -76.32343261,39.59526185 -76.32562404,39.59593849 -76.32628367,39.59441604 -76.3284751,39.59509269 -76.32759628,39.59661513 -76.32781551,39.59661513 -76.32781551,39.59661513 -76.32627937,39.59779926 -76.32781234,39.59915255 -76.32627615,39.60033667 -76.32474318,39.59898338 -76.3240848,39.59949087 -76.32254853,39.60067499 -76.32408171,39.60185912 -76.32254539,39.60304324 -76.32101221,39.60185912 -76.32101221,39.60185912 -76.31947584,39.60304324 -76.32100902,39.60422737 -76.31925334,39.60541149 -76.31772016,39.60422737 -76.31772016,39.60422737 -76.31618368,39.60541149 -76.31771686,39.60659562 -76.31618032,39.60777974 -76.31464715,39.60659562 -76.31464715,39.60659562 -76.31311056,39.60777974 -76.31464374,39.60896387 -76.3131071,39.61014799 -76.31157392,39.60896387 -76.31157392,39.60896387 -76.30981796,39.61014799 -76.31135113,39.61133212 -76.30981439,39.61251624 -76.30828121,39.61133212 -76.30828121,39.61133212 -76.30674442,39.61251624 -76.30827759,39.61370037 -76.30674074,39.61488449 -76.30520757,39.61370037 -76.30520757,39.61370037 -76.30367066,39.61488449 -76.30520384,39.61606862 -76.30344758,39.61725274 -76.30191441,39.61606862 -76.30125598,39.61640694 </coordinates></LineString></MultiGeometry></Placemark><Placemark><name><![CDATA[ENY]]></name><Style><IconStyle><scale>.7</scale><heading>74</heading><Icon><href></href></Icon></IconStyle><LabelStyle><color>ff000000</color><scale>1.0</scale></LabelStyle></Style><Point><extrude>1</extrude><altitudeMode>relativeToGround</altitudeMode><coordinates>-76.300601,39.61463075</coordinates></Point></Placemark><Placemark><name><![CDATA[ENY]]></name><Style><IconStyle><scale>.7</scale><heading>-5</heading><Icon><href></href></Icon></IconStyle><LabelStyle><color>ff000000</color><scale>1.0</scale></LabelStyle></Style><Point><extrude>1</extrude><altitudeMode>relativeToGround</altitudeMode><coordinates>-76.31268939,39.59593849</coordinates></Point></Placemark></Folder>

`

**Comment by spyhunter99** [comment] 2015-06-27 00:37
note, some of the text may be messed up so it may not be syntactically correct

**Comment by mdeutch3** [comment] 2015-06-28 05:52
Black is the default color if line color is not set by the client. To set line color you need to instantiate a MilStdAttributes object, set the line color and then pass it as the 10th parameter if you are calling RenderSymbol.

**Comment by spyhunter99** [comment] 2015-06-28 12:17
This is a behavior change from the previous versions, which set the color (if not defined by the user) based off of the symbol code's identify char, friendly, hostile, neutral, etc. The Obstacle restricted area shows up as the icon preview (render as icon=true) as green, yet it draws as black now. The last version drew as green. This obviously adds some confusion on my part and on the end user.

**Comment by michael-spinelli** [comment] 2015-06-28 13:00
Obstacles that are supposed to show up as green should be green by default if no milstd attribute color is passed in.  Other multipoints should be using affiliation for the default color.  If this isn't happening, it's a bug.

**Comment by mdeutch3** [comment] 2015-06-29 03:33
MilStdSymbol instantiation has been setting the default line color for obstacles and affiliation. That is now being preserved in MultiPointHandler if the line color is not set by the client. the fix has been checked in.

**Comment by michael-spinelli** [comment] 2015-06-29 13:35
Thank Deutch.  Although, looking at the code, I think I introduced that bug.  Sorry about that.  I'll do a release later today.

**Closed by michael-spinelli** 2015-06-29 13:35 UTC
Labels: bug
